server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tDHWHvG8TNEBV1qLKh3
    keySecret: lB3ikdgDGHw45Cb5yCF0e4whjHfO6m
    bucketName: srb-file-0625

